/**
 * This file is part of OGEMA.
 *
 * OGEMA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OGEMA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OGEMA. If not, see <http://www.gnu.org/licenses/>.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogema_hardwaremanager_rpi_NativeAccessImpl */

#ifndef _Included_org_ogema_hardwaremanager_rpi_NativeAccessImpl
#define _Included_org_ogema_hardwaremanager_rpi_NativeAccessImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    getHandles
 * Signature: ()[Lorg/ogema/hardwaremanager/api/Container;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_getHandles
  (JNIEnv *, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    getEvent
 * Signature: (Lorg/ogema/hardwaremanager/api/Container;)Lorg/ogema/hardwaremanager/api/Container;
 */
JNIEXPORT jobject JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_getEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    unblock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_unblock
  (JNIEnv *, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    getIdString
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_getIdString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    getPortString
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_getPortString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    getNativeUsbInfo
 * Signature: (Ljava/lang/Object;Ljava/util/Map;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_getNativeUsbInfo
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
