/**
 * Copyright 2011-2018 Fraunhofer-Gesellschaft zur Förderung der angewandten Wissenschaften e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogema_hardwaremanager_rpi_NativeAccessImpl */

#ifndef _Included_org_ogema_hardwaremanager_rpi_NativeAccessImpl
#define _Included_org_ogema_hardwaremanager_rpi_NativeAccessImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    getHandles
 * Signature: ()[Lorg/ogema/hardwaremanager/api/Container;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_getHandles
  (JNIEnv *, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    getEvent
 * Signature: (Lorg/ogema/hardwaremanager/api/Container;)Lorg/ogema/hardwaremanager/api/Container;
 */
JNIEXPORT jobject JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_getEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    unblock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_unblock
  (JNIEnv *, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    getIdString
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_getIdString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    getPortString
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_getPortString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_ogema_hardwaremanager_rpi_NativeAccessImpl
 * Method:    getNativeUsbInfo
 * Signature: (Ljava/lang/Object;Ljava/util/Map;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_ogema_hardwaremanager_rpi_NativeAccessImpl_getNativeUsbInfo
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
