/**
 * This file is part of OGEMA.
 *
 * OGEMA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3
 * as published by the Free Software Foundation.
 *
 * OGEMA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OGEMA. If not, see <http://www.gnu.org/licenses/>.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogema_hardwaremanager_api_Container */

#ifndef _Included_org_ogema_hardwaremanager_api_Container
#define _Included_org_ogema_hardwaremanager_api_Container
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ogema_hardwaremanager_api_Container_EVENT_NONE
#define org_ogema_hardwaremanager_api_Container_EVENT_NONE 0L
#undef org_ogema_hardwaremanager_api_Container_EVENT_ADD
#define org_ogema_hardwaremanager_api_Container_EVENT_ADD 1L
#undef org_ogema_hardwaremanager_api_Container_EVENT_REMOVE
#define org_ogema_hardwaremanager_api_Container_EVENT_REMOVE 2L
#undef org_ogema_hardwaremanager_api_Container_TYPE_USB
#define org_ogema_hardwaremanager_api_Container_TYPE_USB 1L
#undef org_ogema_hardwaremanager_api_Container_TYPE_SERIAL
#define org_ogema_hardwaremanager_api_Container_TYPE_SERIAL 2L
#undef org_ogema_hardwaremanager_api_Container_TYPE_GPIO
#define org_ogema_hardwaremanager_api_Container_TYPE_GPIO 3L
#ifdef __cplusplus
}
#endif
#endif
