/**
 * Copyright 2011-2018 Fraunhofer-Gesellschaft zur Förderung der angewandten Wissenschaften e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogema_hardwaremanager_api_Container */

#ifndef _Included_org_ogema_hardwaremanager_api_Container
#define _Included_org_ogema_hardwaremanager_api_Container
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ogema_hardwaremanager_api_Container_EVENT_NONE
#define org_ogema_hardwaremanager_api_Container_EVENT_NONE 0L
#undef org_ogema_hardwaremanager_api_Container_EVENT_ADD
#define org_ogema_hardwaremanager_api_Container_EVENT_ADD 1L
#undef org_ogema_hardwaremanager_api_Container_EVENT_REMOVE
#define org_ogema_hardwaremanager_api_Container_EVENT_REMOVE 2L
#undef org_ogema_hardwaremanager_api_Container_TYPE_USB
#define org_ogema_hardwaremanager_api_Container_TYPE_USB 1L
#undef org_ogema_hardwaremanager_api_Container_TYPE_SERIAL
#define org_ogema_hardwaremanager_api_Container_TYPE_SERIAL 2L
#undef org_ogema_hardwaremanager_api_Container_TYPE_GPIO
#define org_ogema_hardwaremanager_api_Container_TYPE_GPIO 3L
#ifdef __cplusplus
}
#endif
#endif
