/**
 * Copyright 2011-2018 Fraunhofer-Gesellschaft zur Förderung der angewandten Wissenschaften e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 08:01:54 AM CEST 
//

package org.ogema.serialization.jaxb;

import static org.ogema.serialization.JaxbResource.NS_OGEMA_REST;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * org.ogema.rest.xml package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Resource_QNAME = new QName(NS_OGEMA_REST, "resource");
	private final static QName _ResourceCollection_QNAME = new QName(NS_OGEMA_REST, "resources");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * org.ogema.rest.xml
	 * 
	 */
	public ObjectFactory() {
	}

	public ResourceCollection createResources() {
		return new ResourceCollection();
	}
	
	/**
	 * Create an instance of {@link Resource }
	 * 
	 */
	public Resource createResource() {
		return new Resource();
	}

	/**
	 * Create an instance of {@link OpaqueResource }
	 * 
	 */
	public OpaqueResource createOpaqueResource() {
		return new OpaqueResource();
	}

	/**
	 * Create an instance of {@link FloatResource }
	 * 
	 */
	public FloatResource createFloatResource() {
		return new FloatResource();
	}

	/**
	 * Create an instance of {@link StringSchedule }
	 * 
	 */
	public StringSchedule createStringSchedule() {
		return new StringSchedule();
	}

	/**
	 * Create an instance of {@link BooleanSchedule }
	 * 
	 */
	public BooleanSchedule createBooleanSchedule() {
		return new BooleanSchedule();
	}

	/**
	 * Create an instance of {@link SampledTime }
	 * 
	 */
	public SampledTime createSampledTime() {
		return new SampledTime();
	}

	/**
	 * Create an instance of {@link SampledOpaque }
	 * 
	 */
	public SampledOpaque createSampledOpaque() {
		return new SampledOpaque();
	}

	/**
	 * Create an instance of {@link IntegerResource }
	 * 
	 */
	public IntegerResource createIntegerResource() {
		return new IntegerResource();
	}

	/**
	 * Create an instance of {@link IntegerSchedule }
	 * 
	 */
	public IntegerSchedule createIntegerSchedule() {
		return new IntegerSchedule();
	}

	/**
	 * Create an instance of {@link SampledFloat }
	 * 
	 */
	public SampledFloat createSampledFloat() {
		return new SampledFloat();
	}

	/**
	 * Create an instance of {@link StringResource }
	 * 
	 */
	public StringResource createStringResource() {
		return new StringResource();
	}

	/**
	 * Create an instance of {@link SampledInteger }
	 * 
	 */
	public SampledInteger createSampledInteger() {
		return new SampledInteger();
	}

	/**
	 * Create an instance of {@link BooleanResource }
	 * 
	 */
	public BooleanResource createBooleanResource() {
		return new BooleanResource();
	}

	/**
	 * Create an instance of {@link OpaqueSchedule }
	 * 
	 */
	public OpaqueSchedule createOpaqueSchedule() {
		return new OpaqueSchedule();
	}

	/**
	 * Create an instance of {@link SampledString }
	 * 
	 */
	public SampledString createSampledString() {
		return new SampledString();
	}

	/**
	 * Create an instance of {@link TimeSchedule }
	 * 
	 */
	public TimeSchedule createTimeSchedule() {
		return new TimeSchedule();
	}

	/**
	 * Create an instance of {@link ResourceLink }
	 * 
	 */
	public ResourceLink createResourceLink() {
		return new ResourceLink();
	}

	/**
	 * Create an instance of {@link SampledBoolean }
	 * 
	 */
	public SampledBoolean createSampledBoolean() {
		return new SampledBoolean();
	}

	/**
	 * Create an instance of {@link FloatSchedule }
	 * 
	 */
	public FloatSchedule createFloatSchedule() {
		return new FloatSchedule();
	}

	/**
	 * Create an instance of {@link TimeResource }
	 * 
	 */
	public TimeResource createTimeResource() {
		return new TimeResource();
	}
	
	public ResourceList createResourceList() {
		return new ResourceList();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Resource }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = NS_OGEMA_REST, name = "resource")
	public JAXBElement<Resource> createResource(Resource value) {
		return new JAXBElement<Resource>(_Resource_QNAME, Resource.class, null, value);
	}
	
	@XmlElementDecl(namespace = NS_OGEMA_REST, name = "resources")
	public JAXBElement<ResourceCollection> createResources(ResourceCollection value) {
		return new JAXBElement<ResourceCollection>(_ResourceCollection_QNAME, ResourceCollection.class, null, value);
	}

}
