/**
 * This file is part of OGEMA.
 *
 * OGEMA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3
 * as published by the Free Software Foundation.
 *
 * OGEMA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OGEMA. If not, see <http://www.gnu.org/licenses/>.
 */
package org.ogema.driver.xbee.serialconnection;

import org.ogema.driver.xbee.Configuration;
import org.ogema.driver.xbee.Constants;
import org.slf4j.Logger;

import jssc.SerialPort;
import jssc.SerialPortException;

public class SerialPortWriter {
	private SerialPort serialPort;

	private final Logger logger = org.slf4j.LoggerFactory.getLogger("xbee-driver");

	public SerialPortWriter(SerialPort serialPort) {
		this.serialPort = serialPort;
	}

	/**
	 * 
	 * @param payload
	 *            The complete XBee frame generated by the FrameFactory.
	 */
	public synchronized void sendData(byte[] payload) {
		try {
			byte[] frame = payload;
			boolean success = serialPort.writeBytes(frame);
			if (Configuration.DEBUG) {
				logger.debug("Successful sent: " + success);
				logger.debug("sendFromFifo:\n " + Constants.bytesToHex(frame));
			}
		} catch (SerialPortException e) {
			e.printStackTrace();
		}
	}
}
