/**
 * Copyright 2011-2018 Fraunhofer-Gesellschaft zur Förderung der angewandten Wissenschaften e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ogema.core.rads.change;

import java.util.concurrent.atomic.AtomicBoolean;

import org.ogema.core.administration.AdminApplication;
import org.ogema.core.application.ApplicationManager;

import org.ogema.core.model.Resource;
import org.ogema.core.resourcemanager.CompoundResourceEvent;
import org.ogema.core.resourcemanager.ResourceValueListener;
import org.ogema.resourcetree.listeners.DefaultCompoundEvent;
import org.ogema.resourcetree.listeners.InternalValueChangedListenerRegistration;

/**
 * Represents a listener registration generated by a call to
 * {@link Resource#addValueListener(org.ogema.core.resourcemanager.ResourceValueListener) }.
 *
 */
// TODO check: no longer implements ResourceListenerRegistration
public class PatternValueChangeListener extends InternalValueChangedListenerRegistration implements ResourceValueListener<Resource> {

	private final Resource target;
	private final boolean callOnEveryUpdate;
	private final ApplicationManager am;
	private final PatternChangeListenerRegistration patternListener;
	private final AtomicBoolean active = new AtomicBoolean(true);

	public PatternValueChangeListener(Resource origin, boolean callOnEveryUpdate, ApplicationManager am, PatternChangeListenerRegistration patternListener) {
		this.target = origin;
		this.callOnEveryUpdate = callOnEveryUpdate;
		this.am = am;
		this.patternListener = patternListener;
	}

	@Override
	public void queueResourceChangedEvent(final Resource r, boolean valueChanged) {
		if ((!callOnEveryUpdate && !valueChanged) || !isActive()) {
			return;
		}
		//ValueEvent ve = new ValueEventImpl(r);
        CompoundResourceEvent<?> e = DefaultCompoundEvent.createResourceUpdatedEvent(r, null, null, valueChanged, active);
		patternListener.trigger(e);
	}

	@Override
	public Resource getResource() {
		return target;
	}

	@Override
	public AdminApplication getApplication() {
		return am.getAdministrationManager().getAppById(am.getAppID().getIDString());
	}

	@Override
	public boolean isCallOnEveryUpdate() {
		return callOnEveryUpdate;
	}

	@Override
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public <T extends Resource> ResourceValueListener<T> getValueListener() {
		return (ResourceValueListener) this;
	}

	@Override
	public void resourceChanged(Resource resource) {
		throw new IllegalStateException("PatternValueChangeListener does not expect any callbacks");
	}
	
	@Override
	public boolean isActive() {
		return active.get();
	}
	
	@Override
	public void dispose() {
		active.set(false);
	}

//	@Override
//	public boolean isAbandoned() {
//		return false;
//	}
//
//	@Override
//	public boolean isRecursive() {
//		return false;
//	}

//	@Override
//	@SuppressWarnings("deprecation")
//	public org.ogema.core.resourcemanager.ResourceListener getListener() {
//		return null;
//	}

}
