/**
 * Copyright 2011-2018 Fraunhofer-Gesellschaft zur Förderung der angewandten Wissenschaften e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ogema.model.targetranges;

import org.ogema.core.model.ValueResource;
import org.ogema.model.prototypes.Data;
import org.ogema.model.ranges.Range;

/**
 * Prototype for control settings that can be attached to any sensor reading
 * or actor switch. This prototype cannot be used by itself. Only models extending
 * this can be created, which then must specify the content of the fields.
 */
public interface TargetRange extends Data {

	/**
	 * Control setpoint for the value. This values shall be reached by
	 * actions of an OGEMA application, no action based on this value is
	 * performed by the framework itself. If no setpoint is given, an estimate
	 * may be guessed from taking the center point of the {@link #targetRange()},
	 *  the {@link #controlLimits() } or the {@link #alarmLimits() } (in descending
	 * order of relevance).
	 * Models inheriting from this prototype must override
	 * this with a suitable simple resource to define the meaning and the unit
	 * of measurement.
	 */
	ValueResource setpoint();

	/**
	 * Range which the sensor value shall lie as a result of control, if possible. The range is considered as soft
	 * limits, i.e. contrary to the {@link #controlLimits() controlLimits} the so-defined ambient range may be left. If
	 * not targetRange is given, the {@link #setpoint() setpoint} may indicate where the range lies.
	 */
	Range targetRange();

	/**
	 * Limits for the sensor value that shall be used for the control of the relevant device. Usually the controlLimits
	 * should be held for sure.
	 */
	Range controlLimits();

	/**
	 * The resource shall only be used for limits that shall be integrated into an alarm logging and/or alarm handling
	 * OGEMA application. It is NOT intended for limits that just trigger control signals.<br>
	 * Note: No alarm events are generated by the OGEMA framework itself.<br>
	 * For sensors providing information not represented as float, a resource of the relevant range type named
	 * <code>alarmLimits</code> can be added as decorator.
	 */
	Range alarmLimits();
}
